[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tictactoe = "6gGrR1fFAkYh6YdsbkrHGgy2jTTzcLKUr1Mzc4Cm17AG"

[programs.devnet]
tictactoe = "6gGrR1fFAkYh6YdsbkrHGgy2jTTzcLKUr1Mzc4Cm17AG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/roman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# AJfVpgRnNYZKvvCqqpUKvYjs3e4qjNvGXZmikBDgUxGw == Idl Account