[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "ZMoUv8yXCJbt4S3S98skMyvsUG5fxfQfkSGT9TzFdFb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/roman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
