[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "Gmr9XQUwL5T9KdDw2Aaude5QyiELrG7E7rq83r886zpV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/roman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
