[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tictactoe = "39YeZsrCamsEh4rjrqGZ74iqEdUwSJAWZhdtkQdP6Tae"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/roman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
